
LOCAL_SRC_FILES += ExynosHWCConfigs.cpp

ifeq ($(BOARD_USES_DISPLAYPORT),true)
    LOCAL_CFLAGS += -DUSE_DISPLAYPORT
endif

ifeq ($(BOARD_USES_HWC_SERVICES),true)
    LOCAL_CFLAGS += -DUSES_HWC_SERVICES
endif

ifeq ($(BOARD_USES_VIRTUAL_DISPLAY),true)
    LOCAL_CFLAGS += -DUSES_VIRTUAL_DISPLAY
endif

ifeq ($(BOARD_USES_DISABLE_COMPOSITIONTYPE_GLES),true)
    LOCAL_CFLAGS += -DUSES_DISABLE_COMPOSITIONTYPE_GLES
endif

ifeq ($(BOARD_USES_SECURE_ENCODER_ONLY),true)
    LOCAL_CFLAGS += -DUSES_SECURE_ENCODER_ONLY
endif

ifeq ($(BOARD_USES_CONTIG_MEMORY_FOR_SCRATCH_BUF),true)
    LOCAL_CFLAGS += -DUSES_CONTIG_MEMORY_FOR_SCRATCH_BUF
endif

ifeq ($(BOARD_USES_HDRUI_GLES_CONVERSION),true)
    LOCAL_CFLAGS += -DUSES_HDR_GLES_CONVERSION
endif

ifdef BOARD_USES_EXYNOS_GRALLOC_VERSION
    LOCAL_CFLAGS += -DGRALLOC_VERSION=$(BOARD_USES_EXYNOS_GRALLOC_VERSION)
endif

ifeq ($(BOARD_USES_HWC_CPU_PERF_MODE),true)
    LOCAL_CFLAGS += -DUSES_CPU_PERF_MODE
endif


