/* copyright Samsung Electronics Co., LTD.
 *
 * This software is proprietary of Samsung Electronics.
 * No part of this software, either material or conceptual may be copied or distributed, transmitted,
 * transcribed, stored in a retrieval system or translated into any human or computer language in any form by any means,
 * electronic, mechanical, manual or otherwise, or disclosed
 * to third parties without the express written permission of Samsung Electronics.
 */


/* RIL OEM  */
#ifndef _RIL_OEM_H
#define _RIL_OEM_H

#ifndef RIL_OEM_REQUEST_BASE
#define RIL_OEM_REQUEST_BASE 10000
#endif

#ifndef RIL_OEM_UNSOL_RESPONSE_BASE
#define RIL_OEM_UNSOL_RESPONSE_BASE 20000
#endif

/******************** OEM  Requests *****************************/
#define RIL_REQUEST_OEM_INVALID                         (0)
#define RIL_REQUEST_OEM_MODEM_DUMP                      (RIL_OEM_REQUEST_BASE + 100)
#define RIL_REQUEST_OEM_VOLUME_SET                      (RIL_OEM_REQUEST_BASE + 101)
#define RIL_REQUEST_OEM_VOLUME_GET                      (RIL_OEM_REQUEST_BASE + 102)
#define RIL_REQUEST_OEM_AUDIO_PATH_SET                  (RIL_OEM_REQUEST_BASE + 103)
#define RIL_REQUEST_OEM_AUDIO_PATH_GET                  (RIL_OEM_REQUEST_BASE + 104)
#define RIL_REQUEST_OEM_MICROPHONE_SET                  (RIL_OEM_REQUEST_BASE + 105)
#define RIL_REQUEST_OEM_MICROPHONE_GET                  (RIL_OEM_REQUEST_BASE + 106)
#define RIL_REQUEST_OEM_SET_PS_ATTACH_DETACH            (RIL_OEM_REQUEST_BASE + 107)
#define RIL_REQUEST_OEM_GET_PS_ATTACH_DETACH            (RIL_OEM_REQUEST_BASE + 108)
#define RIL_REQUEST_OEM_GET_RADIO_STATE                 (RIL_OEM_REQUEST_BASE + 109)

#define RIL_REQUEST_OEM_IMS_SET_CONFIGURATION           (RIL_OEM_REQUEST_BASE + 110)
#define RIL_REQUEST_OEM_IMS_GET_CONFIGURATION           (RIL_OEM_REQUEST_BASE + 111)
#define RIL_REQUEST_OEM_IMS_SIM_AUTH                    (RIL_OEM_REQUEST_BASE + 112)
#define RIL_REQUEST_OEM_IMS_SET_EMERGENCY_CALL_STATUS   (RIL_OEM_REQUEST_BASE + 113)
#define RIL_REQUEST_OEM_IMS_SET_SRVCC_CALL_LIST         (RIL_OEM_REQUEST_BASE + 114)
#define RIL_REQUEST_OEM_IMS_GET_GBA_AUTH                (RIL_OEM_REQUEST_BASE + 115)
#define RIL_REQUEST_OEM_MODEM_RESET                     (RIL_OEM_REQUEST_BASE + 116)

#define RIL_REQUEST_OEM_GET_MANUAL_RAT_MODE             (RIL_OEM_REQUEST_BASE + 117)
#define RIL_REQUEST_OEM_SET_MANUAL_RAT_MODE             (RIL_OEM_REQUEST_BASE + 118)
#define RIL_REQUEST_OEM_GET_FREQUENCY_LOCK              (RIL_OEM_REQUEST_BASE + 119)
#define RIL_REQUEST_OEM_SET_FREQUENCY_LOCK              (RIL_OEM_REQUEST_BASE + 120)
#define RIL_REQUEST_OEM_SET_ENDC_MODE                   (RIL_OEM_REQUEST_BASE + 121)
#define RIL_REQUEST_OEM_GET_ENDC_MODE                   (RIL_OEM_REQUEST_BASE + 122)
#define RIL_REQUEST_OEM_IMS_SIM_IO                      (RIL_OEM_REQUEST_BASE + 123)
#define RIL_REQUEST_OEM_SET_IMS_TEST_MODE               (RIL_OEM_REQUEST_BASE + 124)

#define RIL_REQUEST_OEM_AUDIO_CLOCK_SET                 (RIL_OEM_REQUEST_BASE + 126)
#define RIL_REQUEST_OEM_AUDIO_LOOPBACK_SET              (RIL_OEM_REQUEST_BASE + 127)
#define RIL_REQUEST_OEM_SET_TTY_MODE                    (RIL_OEM_REQUEST_BASE + 128)
#define RIL_REQUEST_OEM_SET_UICC_SUBSCRIPTION           (RIL_OEM_REQUEST_BASE + 129)

#define RIL_REQUEST_OEM_SET_ENG_MODE                    (RIL_OEM_REQUEST_BASE + 130)
#define RIL_REQUEST_OEM_SET_SCR_LINE                    (RIL_OEM_REQUEST_BASE + 131)
#define RIL_REQUEST_OEM_SET_DEBUG_TRACE                 (RIL_OEM_REQUEST_BASE + 132)
#define RIL_REQUEST_OEM_CANCEL_AVAILABLE_NETWORKS       (RIL_OEM_REQUEST_BASE + 133)
#define RIL_REQUEST_OEM_SIM_AUTHENTICATION              (RIL_OEM_REQUEST_BASE + 134)
#define RIL_REQUEST_OEM_IF_EXECUTE_AM                   (RIL_OEM_REQUEST_BASE + 135)

#define RIL_REQUEST_OEM_SET_CARRIER_CONFIG              (RIL_OEM_REQUEST_BASE + 139)
#define RIL_REQUEST_OEM_SET_ENG_STRING_INPUT            (RIL_OEM_REQUEST_BASE + 140)
#define RIL_REQUEST_OEM_APN_SETTINGS                    (RIL_OEM_REQUEST_BASE + 141)
#define RIL_REQUEST_OEM_GET_MSL_CODE                    (RIL_OEM_REQUEST_BASE + 142)
#define RIL_REQUEST_OEM_SET_PIN_CONTROL                 (RIL_OEM_REQUEST_BASE + 143)
#define RIL_REQUEST_OEM_SEND_SGC                        (RIL_OEM_REQUEST_BASE + 144)
#define RIL_REQUEST_OEM_GET_MANUAL_BAND_MODE            (RIL_OEM_REQUEST_BASE + 145)
#define RIL_REQUEST_OEM_SET_MANUAL_BAND_MODE            (RIL_OEM_REQUEST_BASE + 146)
#define RIL_REQUEST_OEM_GET_RF_DESENSE_MODE             (RIL_OEM_REQUEST_BASE + 147)
#define RIL_REQUEST_OEM_SET_RF_DESENSE_MODE             (RIL_OEM_REQUEST_BASE + 148)
#define RIL_REQUEST_OEM_GET_IMS_SUPPORT_SERVICE         (RIL_OEM_REQUEST_BASE + 149)

//AIMS support start ---------------------
#define RIL_REQUEST_OEM_AIMS_DIAL                       (RIL_OEM_REQUEST_BASE + 150)
#define RIL_REQUEST_OEM_AIMS_ANSWER                     (RIL_OEM_REQUEST_BASE + 151)
#define RIL_REQUEST_OEM_AIMS_HANGUP                     (RIL_OEM_REQUEST_BASE + 152)
#define RIL_REQUEST_OEM_AIMS_DEREGISTRATION             (RIL_OEM_REQUEST_BASE + 153)
#define RIL_REQUEST_OEM_AIMS_HIDDEN_MENU                (RIL_OEM_REQUEST_BASE + 154)
#define RIL_REQUEST_OEM_AIMS_ADD_PDN_INFO               (RIL_OEM_REQUEST_BASE + 155)
#define RIL_REQUEST_OEM_AIMS_CALL_MANAGE                (RIL_OEM_REQUEST_BASE + 156)
#define RIL_REQUEST_OEM_AIMS_SEND_DTMF                  (RIL_OEM_REQUEST_BASE + 157)
#define RIL_REQUEST_OEM_AIMS_SET_FRAME_TIME             (RIL_OEM_REQUEST_BASE + 158)
#define RIL_REQUEST_OEM_AIMS_GET_FRAME_TIME             (RIL_OEM_REQUEST_BASE + 159)
#define RIL_REQUEST_OEM_AIMS_CALL_MODIFY                (RIL_OEM_REQUEST_BASE + 160)
#define RIL_REQUEST_OEM_AIMS_RESPONSE_CALL_MODIFY       (RIL_OEM_REQUEST_BASE + 161)
#define RIL_REQUEST_OEM_AIMS_TIME_INFO                  (RIL_OEM_REQUEST_BASE + 162)
#define RIL_REQUEST_OEM_AIMS_CONF_CALL_ADD_REMOVE_USER  (RIL_OEM_REQUEST_BASE + 163)
#define RIL_REQUEST_OEM_AIMS_ENHANCED_CONF_CALL         (RIL_OEM_REQUEST_BASE + 164)
#define RIL_REQUEST_OEM_AIMS_GET_CALL_FORWARD_STATUS    (RIL_OEM_REQUEST_BASE + 165)
#define RIL_REQUEST_OEM_AIMS_SET_CALL_FORWARD_STATUS    (RIL_OEM_REQUEST_BASE + 166)
#define RIL_REQUEST_OEM_AIMS_GET_CALL_WAITING           (RIL_OEM_REQUEST_BASE + 167)
#define RIL_REQUEST_OEM_AIMS_SET_CALL_WAITING           (RIL_OEM_REQUEST_BASE + 168)
#define RIL_REQUEST_OEM_AIMS_GET_CALL_BARRING           (RIL_OEM_REQUEST_BASE + 169)
#define RIL_REQUEST_OEM_AIMS_SET_CALL_BARRING           (RIL_OEM_REQUEST_BASE + 170)
#define RIL_REQUEST_OEM_AIMS_SEND_SMS                   (RIL_OEM_REQUEST_BASE + 171)
#define RIL_REQUEST_OEM_AIMS_SEND_EXPECT_MORE           (RIL_OEM_REQUEST_BASE + 172)
#define RIL_REQUEST_OEM_AIMS_SEND_SMS_ACK               (RIL_OEM_REQUEST_BASE + 173)
#define RIL_REQUEST_OEM_AIMS_SEND_ACK_INCOMING_SMS      (RIL_OEM_REQUEST_BASE + 174)
#define RIL_REQUEST_OEM_AIMS_CHG_BARRING_PWD            (RIL_OEM_REQUEST_BASE + 175)
#define RIL_REQUEST_OEM_AIMS_SEND_USSD_INFO             (RIL_OEM_REQUEST_BASE + 176)
#define RIL_REQUEST_OEM_AIMS_GET_PRESENTATION_SETTINGS  (RIL_OEM_REQUEST_BASE + 177)
#define RIL_REQUEST_OEM_AIMS_SET_PRESENTATION_SETTINGS  (RIL_OEM_REQUEST_BASE + 178)
#define RIL_REQUEST_OEM_AIMS_SET_SELF_CAPABILITY        (RIL_OEM_REQUEST_BASE + 179)
#define RIL_REQUEST_OEM_AIMS_HO_TO_WIFI_READY           (RIL_OEM_REQUEST_BASE + 180)
#define RIL_REQUEST_OEM_AIMS_HO_TO_WIFI_CANCEL_IND      (RIL_OEM_REQUEST_BASE + 181)
#define RIL_REQUEST_OEM_AIMS_HO_PAYLOAD_IND             (RIL_OEM_REQUEST_BASE + 182)
#define RIL_REQUEST_OEM_AIMS_HO_TO_3GPP                 (RIL_OEM_REQUEST_BASE + 183)
#define RIL_REQUEST_OEM_AIMS_SEND_ACK_INCOMING_CDMA_SMS (RIL_OEM_REQUEST_BASE + 184)
#define RIL_REQUEST_OEM_AIMS_MEDIA_STATE_IND            (RIL_OEM_REQUEST_BASE + 185)
#define RIL_REQUEST_OEM_AIMS_DEL_PDN_INFO               (RIL_OEM_REQUEST_BASE + 186)
#define RIL_REQUEST_OEM_AIMS_STACK_START_REQ            (RIL_OEM_REQUEST_BASE + 187)
#define RIL_REQUEST_OEM_AIMS_STACK_STOP_REQ             (RIL_OEM_REQUEST_BASE + 188)
#define RIL_REQUEST_OEM_AIMS_XCAPM_START_REQ            (RIL_OEM_REQUEST_BASE + 189)
#define RIL_REQUEST_OEM_AIMS_XCAPM_STOP_REQ             (RIL_OEM_REQUEST_BASE + 190)
#define RIL_REQUEST_OEM_AIMS_RTT_SEND_TEXT              (RIL_OEM_REQUEST_BASE + 191)
#define RIL_REQUEST_OEM_AIMS_EXIT_EMERGENCY_CB_MODE     (RIL_OEM_REQUEST_BASE + 192)
#define RIL_REQUEST_OEM_AIMS_SET_GEO_LOCATION_INFO      (RIL_OEM_REQUEST_BASE + 193)
#define RIL_REQUEST_OEM_AIMS_CDMA_SEND_SMS              (RIL_OEM_REQUEST_BASE + 194)
#define RIL_REQUEST_OEM_AIMS_SET_PDN_EST_STATUS         (RIL_OEM_REQUEST_BASE + 195)
#define RIL_REQUEST_OEM_AIMS_SET_HIDDEN_MENU_ITEM       (RIL_OEM_REQUEST_BASE + 196)
#define RIL_REQUEST_OEM_AIMS_GET_HIDDEN_MENU_ITEM       (RIL_OEM_REQUEST_BASE + 197)
#define RIL_REQUEST_OEM_AIMS_SET_RTP_RX_STATISTICS      (RIL_OEM_REQUEST_BASE + 198)
//AIMS support end ---------------------

//AGPS support start ---------------------
#define RIL_REQUEST_OEM_GPS_SET_FREQUENCY_AIDING                (RIL_OEM_REQUEST_BASE + 200)
#define RIL_REQUEST_OEM_GPS_GET_LPP_SUPL_REQ_ECID_INFO          (RIL_OEM_REQUEST_BASE + 201)
#define RIL_REQUEST_OEM_GPS_SET_RRLP_SUPL_REQ_ECID_INFO         (RIL_OEM_REQUEST_BASE + 202)
#define RIL_REQUEST_OEM_GPS_MO_LOCATION_REQUEST                 (RIL_OEM_REQUEST_BASE + 203)
#define RIL_REQUEST_OEM_GPS_GET_LPP_REQ_SERVING_CELL_INFO       (RIL_OEM_REQUEST_BASE + 204)
#define RIL_REQUEST_OEM_GPS_SET_SUPL_NI_READY                   (RIL_OEM_REQUEST_BASE + 205)
#define RIL_REQUEST_OEM_GPS_GET_GSM_EXT_INFO_MSG                (RIL_OEM_REQUEST_BASE + 221)
#define RIL_REQUEST_OEM_GPS_CONTROL_PLANE_ENABLE                (RIL_OEM_REQUEST_BASE + 222)
#define RIL_REQUEST_OEM_GPS_GNSS_LPP_PROFILE_SET                (RIL_OEM_REQUEST_BASE + 223)

// Indication from AP, No resp
#define RIL_REQUEST_OEM_GPS_MEASURE_POS_RSP                     (RIL_OEM_REQUEST_BASE + 206)
#define RIL_REQUEST_OEM_GPS_RELEASE_GPS                         (RIL_OEM_REQUEST_BASE + 207)
#define RIL_REQUEST_OEM_GPS_MT_LOCATION_REQUEST                 (RIL_OEM_REQUEST_BASE + 208)
#define RIL_REQUEST_OEM_GPS_LPP_PROVIDE_CAPABILITIES            (RIL_OEM_REQUEST_BASE + 209)
#define RIL_REQUEST_OEM_GPS_LPP_REQUEST_ASSIST_DATA             (RIL_OEM_REQUEST_BASE + 210)
#define RIL_REQUEST_OEM_GPS_LPP_PROVIDE_LOCATION_INFO           (RIL_OEM_REQUEST_BASE + 211)
#define RIL_REQUEST_OEM_GPS_LPP_GPS_ERROR_IND                   (RIL_OEM_REQUEST_BASE + 212)
#define RIL_REQUEST_OEM_GPS_SUPL_LPP_DATA_INFO                  (RIL_OEM_REQUEST_BASE + 213)
#define RIL_REQUEST_OEM_GPS_SUPL_NI_MESSAGE                     (RIL_OEM_REQUEST_BASE + 214)
#define RIL_REQUEST_OEM_GPS_RETRIEVE_LOC_INFO                   (RIL_OEM_REQUEST_BASE + 224)

// for CDMA & HEDGE GANSS
#define RIL_REQUEST_OEM_GPS_SET_GANSS_MEAS_POS_RSP              (RIL_OEM_REQUEST_BASE + 215)
#define RIL_REQUEST_OEM_GPS_SET_GPS_LOCK_MODE                   (RIL_OEM_REQUEST_BASE + 216)
#define RIL_REQUEST_OEM_GPS_GET_REFERENCE_LOCATION              (RIL_OEM_REQUEST_BASE + 217)
#define RIL_REQUEST_OEM_GPS_SET_PSEUDO_RANGE_MEASUREMENTS       (RIL_OEM_REQUEST_BASE + 218)
#define RIL_REQUEST_OEM_GPS_GET_CDMA_PRECISE_TIME_AIDING_INFO   (RIL_OEM_REQUEST_BASE + 219)
#define RIL_REQUEST_OEM_GPS_CDMA_FREQ_AIDING                    (RIL_OEM_REQUEST_BASE + 225)

// Indication from AP, No resp
#define RIL_REQUEST_OEM_GPS_GANSS_AP_POS_CAP_RSP                (RIL_OEM_REQUEST_BASE + 220)
//AGPS support end ---------------------

/* getAvilableNetwork with RAN(Radio Access Network) */
#define RIL_REQUEST_OEM_GET_AVAILABLE_NETWORKS              (RIL_OEM_REQUEST_BASE + 230)
#define RIL_REQUEST_OEM_GET_FREQUENCY_INFO                  (RIL_OEM_REQUEST_BASE + 231)

/* WFC */
#define RIL_REQUEST_OEM_WFC_MEDIA_CHANNEL_CONFIG            (RIL_OEM_REQUEST_BASE + 300)
#define RIL_REQUEST_OEM_WFC_DTMF_START                      (RIL_OEM_REQUEST_BASE + 301)
#define RIL_REQUEST_OEM_WFC_SET_VOWIFI_HO_THRESHOLD         (RIL_OEM_REQUEST_BASE + 302)

// Secure Element
#define RIL_REQUEST_OEM_SIM_OPEN_CHANNEL                        (RIL_OEM_REQUEST_BASE + 401)
#define RIL_REQUEST_OEM_SIM_TRANSMIT_APDU_LOGICAL               (RIL_OEM_REQUEST_BASE + 402)
#define RIL_REQUEST_OEM_SIM_TRANSMIT_APDU_BASIC                 (RIL_OEM_REQUEST_BASE + 403)
#define RIL_REQUEST_OEM_SIM_PRESENT                             (RIL_OEM_REQUEST_BASE + 404)

// RSSI SCAN
#define RIL_REQUEST_OEM_SCAN_RSSI                               (RIL_OEM_REQUEST_BASE + 420)

// AT command through RIL path
#define RIL_REQUEST_OEM_FORWARDING_AT_COMMAND                   (RIL_OEM_REQUEST_BASE + 421)

// CP Sleep Log
#define RIL_REQUEST_OEM_SET_MODEM_LOG_DUMP                      (RIL_OEM_REQUEST_BASE + 422)

#define RIL_REQUEST_OEM_SET_PREFERRED_CALL_CAPABILITY           (RIL_OEM_REQUEST_BASE + 450)
#define RIL_REQUEST_OEM_GET_PREFERRED_CALL_CAPABILITY           (RIL_OEM_REQUEST_BASE + 451)
#define RIL_REQUEST_OEM_TS25TABLE_DUMP                          (RIL_OEM_REQUEST_BASE + 452)

// RCS command
#define RIL_REQUEST_OEM_AIMS_RCS_MULTI_FRAME            (RIL_OEM_REQUEST_BASE + 501)
#define RIL_REQUEST_OEM_AIMS_RCS_CHAT                   (RIL_OEM_REQUEST_BASE + 502)
#define RIL_REQUEST_OEM_AIMS_RCS_GROUP_CHAT             (RIL_OEM_REQUEST_BASE + 503)
#define RIL_REQUEST_OEM_AIMS_RCS_OFFLINE_MODE           (RIL_OEM_REQUEST_BASE + 504)
#define RIL_REQUEST_OEM_AIMS_RCS_FILE_TRANSFER          (RIL_OEM_REQUEST_BASE + 505)
#define RIL_REQUEST_OEM_AIMS_RCS_COMMON_MESSAGE         (RIL_OEM_REQUEST_BASE + 506)
#define RIL_REQUEST_OEM_AIMS_RCS_CONTENT_SHARE          (RIL_OEM_REQUEST_BASE + 507)
#define RIL_REQUEST_OEM_AIMS_RCS_PRESENCE               (RIL_OEM_REQUEST_BASE + 508)
#define RIL_REQUEST_OEM_AIMS_XCAP_MANAGE                (RIL_OEM_REQUEST_BASE + 509)
#define RIL_REQUEST_OEM_AIMS_RCS_CONFIG_MANAGE          (RIL_OEM_REQUEST_BASE + 510)
#define RIL_REQUEST_OEM_AIMS_RCS_TLS_MANAGE             (RIL_OEM_REQUEST_BASE + 511)

/* eMBMS */
#define RIL_REQUEST_OEM_EMBMS_ENABLE_SERVICE            (RIL_OEM_REQUEST_BASE + 550)
#define RIL_REQUEST_OEM_EMBMS_DISABLE_SERVICE           (RIL_OEM_REQUEST_BASE + 551)
#define RIL_REQUEST_OEM_EMBMS_SET_SESSION               (RIL_OEM_REQUEST_BASE + 552)
#define RIL_REQUEST_OEM_EMBMS_GET_SESSION_LIST          (RIL_OEM_REQUEST_BASE + 553)
#define RIL_REQUEST_OEM_EMBMS_GET_SIGNAL_STRENGTH       (RIL_OEM_REQUEST_BASE + 554)
#define RIL_REQUEST_OEM_EMBMS_GET_NETWORK_TIME          (RIL_OEM_REQUEST_BASE + 555)
#define RIL_REQUEST_OEM_EMBMS_CHECK_AVAIABLE_EMBMS      (RIL_OEM_REQUEST_BASE + 556)


/*
 * OEM specific
 */
#define RIL_REQUEST_OEM_SPECIFIC_BASE                       (RIL_OEM_REQUEST_BASE + 1000)
/******************** OEM1 ********************/
#define RIL_REQUEST_OEM_STORE_ADB_SERIAL_NUMBER             (RIL_REQUEST_OEM_SPECIFIC_BASE + 1)
#define RIL_REQUEST_OEM_READ_ADB_SERIAL_NUMBER              (RIL_REQUEST_OEM_SPECIFIC_BASE + 2)

/******************** OEM2 ********************/
/* P-SENSOR */
#define RIL_REQUEST_OEM_PSENSOR_SET_STATUS                  (RIL_REQUEST_OEM_SPECIFIC_BASE + 11)
#define RIL_UNSOL_OEM_PSENSOR_CONTROL_STATE                 (RIL_REQUEST_OEM_SPECIFIC_BASE + 12)
#define RIL_REQUEST_OEM_SET_CA_BANDWIDTH_FILTER             (RIL_REQUEST_OEM_SPECIFIC_BASE + 13)
#define RIL_REQUEST_OEM_ICC_DEPERSONALIZATION               (RIL_REQUEST_OEM_SPECIFIC_BASE + 14)

/* VSIM */
#define RIL_REQUEST_OEM_VSIM_NOTIFICATION                   (RIL_REQUEST_OEM_SPECIFIC_BASE + 21)
#define RIL_REQUEST_OEM_VSIM_OPERATION                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 22)

/* SAR */
#define RIL_REQUEST_OEM_SAR_SET_STATE                       (RIL_REQUEST_OEM_SPECIFIC_BASE + 31)
#define RIL_REQUEST_OEM_SAR_GET_STATE                       (RIL_REQUEST_OEM_SPECIFIC_BASE + 32)

#define RIL_REQUEST_OEM_GET_RADIO_NODE                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 100)
#define RIL_REQUEST_OEM_SET_RADIO_NODE                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 101)
#define RIL_REQUEST_OEM_GET_PROVISION_UPDATE_REQUEST        (RIL_REQUEST_OEM_SPECIFIC_BASE + 102)
#define RIL_REQUEST_OEM_SET_PROVISION_UPDATE_DONE_REQUEST   (RIL_REQUEST_OEM_SPECIFIC_BASE + 103)
#define RIL_REQUEST_OEM_RADIO_CONFIG_RESET                  (RIL_REQUEST_OEM_SPECIFIC_BASE + 104)

/* SE13 Table */
#define RIL_REQUEST_OEM_GET_PLMN_NAME_FROM_SE13TABLE        0x0A0006

/******************** OEM5 ********************/
#define RIL_REQUEST_OEM_SET_SELFLOG                         (RIL_REQUEST_OEM_SPECIFIC_BASE + 40)
#define RIL_REQUEST_OEM_GET_SELFLOG_STATUS                  (RIL_REQUEST_OEM_SPECIFIC_BASE + 41)
#define RIL_REQUEST_OEM_MODEM_INFO                          (RIL_REQUEST_OEM_SPECIFIC_BASE + 42)
#define RIL_REQUEST_OEM_SET_RTP_PKTLOSS_THRESHOLD           (RIL_REQUEST_OEM_SPECIFIC_BASE + 43)
#define RIL_REQUEST_OEM_SWITCH_MODEM_FUNCTION               (RIL_REQUEST_OEM_SPECIFIC_BASE + 44)
#define RIL_REQUEST_OEM_REQ_SET_PDCP_DISCARD_TIMER          (RIL_REQUEST_OEM_SPECIFIC_BASE + 45)
#define RIL_REQUEST_OEM_GET_CQI_INFO                        (RIL_REQUEST_OEM_SPECIFIC_BASE + 46)
#define RIL_REQUEST_OEM_SET_SAR_SETTING                     (RIL_REQUEST_OEM_SPECIFIC_BASE + 47)
#define RIL_REQUEST_OEM_SET_GMO_SWITCH                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 48)
#define RIL_REQUEST_OEM_SET_TCS_FCI                         (RIL_REQUEST_OEM_SPECIFIC_BASE + 49)
#define RIL_REQUEST_OEM_GET_TCS_FCI                         (RIL_REQUEST_OEM_SPECIFIC_BASE + 50)
#define RIL_REQUEST_OEM_SET_SELFLOG_PROFILE                 (RIL_REQUEST_OEM_SPECIFIC_BASE + 51)
#define RIL_REQUEST_OEM_SET_FORBID_LTE_CELL                 (RIL_REQUEST_OEM_SPECIFIC_BASE + 52)
#define RIL_REQUEST_OEM_SET_ELEVATOR_SENSOR                 (RIL_REQUEST_OEM_SPECIFIC_BASE + 53)

/******************** OEM Unsolicited responses ********************/
#define RIL_UNSOL_OEM_IMS_CONFIGURATION         (RIL_OEM_UNSOL_RESPONSE_BASE + 101)
#define RIL_UNSOL_OEM_IMS_DEDICATED_PDN_INFO    (RIL_OEM_UNSOL_RESPONSE_BASE + 102)
#define RIL_UNSOL_OEM_IMS_EMERGENCY_ACT_INFO    (RIL_OEM_UNSOL_RESPONSE_BASE + 103)
#define RIL_UNSOL_OEM_IMS_SET_SRVCC_INFO        (RIL_OEM_UNSOL_RESPONSE_BASE + 104)
#define RIL_UNSOL_OEM_IMS_EMERGENCY_CALL_LIST   (RIL_OEM_UNSOL_RESPONSE_BASE + 105)
#define RIL_UNSOL_OEM_IMS_SUPPORT_SERVICE       (RIL_OEM_UNSOL_RESPONSE_BASE + 106)
#define RIL_UNSOL_OEM_IMS_OPEN_CARRIER_INFO     (RIL_OEM_UNSOL_RESPONSE_BASE + 107)
#define RIL_UNSOL_OEM_SCAN_RSSI_RESULT          (RIL_OEM_UNSOL_RESPONSE_BASE + 108)
#define RIL_UNSOL_OEM_FORWARDING_AT_COMMAND     (RIL_OEM_UNSOL_RESPONSE_BASE + 109)
#define RIL_UNSOL_OEM_RINGBACK_TONE_BY_NETWORK  (RIL_OEM_UNSOL_RESPONSE_BASE + 110)


//AIMS support start ---------------------
#define RIL_UNSOL_OEM_AIMS_CALL_RING                    (RIL_OEM_UNSOL_RESPONSE_BASE + 131)
#define RIL_UNSOL_OEM_AIMS_CALL_STATUS                  (RIL_OEM_UNSOL_RESPONSE_BASE + 132)
#define RIL_UNSOL_OEM_AIMS_REGISTRATION                 (RIL_OEM_UNSOL_RESPONSE_BASE + 133)
#define RIL_UNSOL_OEM_AIMS_CALL_MODIFY                  (RIL_OEM_UNSOL_RESPONSE_BASE + 134)
#define RIL_UNSOL_OEM_AIMS_FRAME_TIME                   (RIL_OEM_UNSOL_RESPONSE_BASE + 135)
#define RIL_UNSOL_OEM_AIMS_SUPP_SVC_NOTIFICATION        (RIL_OEM_UNSOL_RESPONSE_BASE + 136)
#define RIL_UNSOL_OEM_AIMS_NEW_SMS                      (RIL_OEM_UNSOL_RESPONSE_BASE + 137)
#define RIL_UNSOL_OEM_AIMS_NEW_SMS_STATUS_REPORT        (RIL_OEM_UNSOL_RESPONSE_BASE + 138)
#define RIL_UNSOL_OEM_AIMS_ON_USSD                      (RIL_OEM_UNSOL_RESPONSE_BASE + 139)
#define RIL_UNSOL_OEM_AIMS_CONFERENCE_CALL_EVENT        (RIL_OEM_UNSOL_RESPONSE_BASE + 140)
#define RIL_UNSOL_OEM_AIMS_PAYLOAD_INFO                 (RIL_OEM_UNSOL_RESPONSE_BASE + 141)
#define RIL_UNSOL_OEM_AIMS_VOWIFI_HO_CALL_INFO          (RIL_OEM_UNSOL_RESPONSE_BASE + 142)
#define RIL_UNSOL_OEM_AIMS_NEW_CDMA_SMS                 (RIL_OEM_UNSOL_RESPONSE_BASE + 143)
#define RIL_UNSOL_OEM_AIMS_RINGBACK_TONE                (RIL_OEM_UNSOL_RESPONSE_BASE + 144)
#define RIL_UNSOL_OEM_AIMS_CALL_MANAGE                  (RIL_OEM_UNSOL_RESPONSE_BASE + 145)
#define RIL_UNSOL_OEM_AIMS_CONF_CALL_ADD_REMOVE_USER    (RIL_OEM_UNSOL_RESPONSE_BASE + 146)
#define RIL_UNSOL_OEM_AIMS_ENHANCED_CONF_CALL           (RIL_OEM_UNSOL_RESPONSE_BASE + 147)
#define RIL_UNSOL_OEM_AIMS_CALL_MODIFY_RSP              (RIL_OEM_UNSOL_RESPONSE_BASE + 148)
#define RIL_UNSOL_OEM_AIMS_DTMF_EVENT                   (RIL_OEM_UNSOL_RESPONSE_BASE + 149)
#define RIL_UNSOL_OEM_AIMS_RTT_NEW_TEXT                 (RIL_OEM_UNSOL_RESPONSE_BASE + 150)
#define RIL_UNSOL_OEM_AIMS_RTT_FAIL_SENDING_TEXT        (RIL_OEM_UNSOL_RESPONSE_BASE + 151)
#define RIL_UNSOL_OEM_AIMS_RCS_MULTI_FRAME              (RIL_OEM_UNSOL_RESPONSE_BASE + 152)
#define RIL_UNSOL_OEM_AIMS_RCS_CHAT                     (RIL_OEM_UNSOL_RESPONSE_BASE + 153)
#define RIL_UNSOL_OEM_AIMS_RCS_GROUP_CHAT               (RIL_OEM_UNSOL_RESPONSE_BASE + 154)
#define RIL_UNSOL_OEM_AIMS_RCS_OFFLINE_MODE             (RIL_OEM_UNSOL_RESPONSE_BASE + 155)
#define RIL_UNSOL_OEM_AIMS_RCS_FILE_TRANSFER            (RIL_OEM_UNSOL_RESPONSE_BASE + 156)
#define RIL_UNSOL_OEM_AIMS_RCS_COMMON_MESSAGE           (RIL_OEM_UNSOL_RESPONSE_BASE + 157)
#define RIL_UNSOL_OEM_AIMS_RCS_CONTENT_SHARE            (RIL_OEM_UNSOL_RESPONSE_BASE + 158)
#define RIL_UNSOL_OEM_AIMS_RCS_PRESENCE                 (RIL_OEM_UNSOL_RESPONSE_BASE + 159)
#define RIL_UNSOL_OEM_AIMS_RCS_XCAP_MANAGE              (RIL_OEM_UNSOL_RESPONSE_BASE + 160)
#define RIL_UNSOL_OEM_AIMS_RCS_CONFIG_MANAGE            (RIL_OEM_UNSOL_RESPONSE_BASE + 161)
#define RIL_UNSOL_OEM_AIMS_RCS_TLS_MANAGE               (RIL_OEM_UNSOL_RESPONSE_BASE + 162)
#define RIL_UNSOL_OEM_AIMS_EXIT_EMERGENCY_CB_MODE       (RIL_OEM_UNSOL_RESPONSE_BASE + 163)
#define RIL_UNSOL_OEM_AIMS_AC_BARRING_INFO              (RIL_OEM_UNSOL_RESPONSE_BASE + 164)
#define RIL_UNSOL_OEM_AIMS_DIALOG_INFO                  (RIL_OEM_UNSOL_RESPONSE_BASE + 165)
#define RIL_UNSOL_OEM_AIMS_MEDIA_STATUS                 (RIL_OEM_UNSOL_RESPONSE_BASE + 166)
#define RIL_UNSOL_OEM_AIMS_SIP_MSG_INFO                 (RIL_OEM_UNSOL_RESPONSE_BASE + 167)
#define RIL_UNSOL_OEM_AIMS_VOICE_RTP_QUALITY            (RIL_OEM_UNSOL_RESPONSE_BASE + 168)
#define RIL_UNSOL_OEM_AIMS_RTP_RX_STATISTICS            (RIL_OEM_UNSOL_RESPONSE_BASE + 169)
//AIMS support end ---------------------

//AGPS support start ---------------------
#define RIL_UNSOL_OEM_GPS_MEASURE_POS_REQ                       (RIL_OEM_UNSOL_RESPONSE_BASE + 170)
#define RIL_UNSOL_OEM_GPS_ASSIST_DATA                           (RIL_OEM_UNSOL_RESPONSE_BASE + 171)
#define RIL_UNSOL_OEM_GPS_RELEASE_GPS                           (RIL_OEM_UNSOL_RESPONSE_BASE + 172)
#define RIL_UNSOL_OEM_GPS_MT_LOCATION_REQUEST                   (RIL_OEM_UNSOL_RESPONSE_BASE + 173)
#define RIL_UNSOL_OEM_GPS_RESET_GPS_ASSIST_DATA                 (RIL_OEM_UNSOL_RESPONSE_BASE + 174)
#define RIL_UNSOL_OEM_GPS_LPP_REQUEST_CAPABILITIES              (RIL_OEM_UNSOL_RESPONSE_BASE + 175)
#define RIL_UNSOL_OEM_GPS_LPP_PROVIDE_ASSIST_DATA               (RIL_OEM_UNSOL_RESPONSE_BASE + 176)
#define RIL_UNSOL_OEM_GPS_LPP_REQUEST_LOCATION_INFO             (RIL_OEM_UNSOL_RESPONSE_BASE + 177)
#define RIL_UNSOL_OEM_GPS_LPP_GPS_ERROR_IND                     (RIL_OEM_UNSOL_RESPONSE_BASE + 178)
#define RIL_UNSOL_OEM_GPS_SUPL_LPP_DATA_INFO                    (RIL_OEM_UNSOL_RESPONSE_BASE + 179)
#define RIL_UNSOL_OEM_GPS_SUPL_NI_MESSAGE                       (RIL_OEM_UNSOL_RESPONSE_BASE + 180)
#define RIL_UNSOL_OEM_GPS_SUPL_NI_READY                         (RIL_OEM_UNSOL_RESPONSE_BASE + 187)
#define RIL_UNSOL_OEM_GPS_START_MDT_LOC                         (RIL_OEM_UNSOL_RESPONSE_BASE + 188)
#define RIL_UNSOL_OEM_GPS_LPP_UPDATE_UE_LOC_INFO                (RIL_OEM_UNSOL_RESPONSE_BASE + 189)
#define RIL_UNSOL_OEM_GPS_LOCK_MODE                             (RIL_OEM_UNSOL_RESPONSE_BASE + 190)
// CDMA & HEDGE GANSS
#define RIL_UNSOL_OEM_GPS_3GPP_SEND_GANSS_ASSIT_DATA            (RIL_OEM_UNSOL_RESPONSE_BASE + 181)
#define RIL_UNSOL_OEM_GPS_GANSS_MEAS_POS_MSG                    (RIL_OEM_UNSOL_RESPONSE_BASE + 182)
#define RIL_UNSOL_OEM_GPS_CDMA_GPS_POWER_ON                     (RIL_OEM_UNSOL_RESPONSE_BASE + 183)
#define RIL_UNSOL_OEM_GPS_CDMA_SEND_ACQUSITION_ASSIT_DATA       (RIL_OEM_UNSOL_RESPONSE_BASE + 184)
#define RIL_UNSOL_OEM_GPS_CDMA_SESSION_CANCELLATION             (RIL_OEM_UNSOL_RESPONSE_BASE + 185)
#define RIL_UNSOL_OEM_GPS_GANSS_AP_POS_CAP_REQ                  (RIL_OEM_UNSOL_RESPONSE_BASE + 186)
//AGPS support end ---------------------

// Telephony Utils
#define RIL_UNSOL_OEM_DISPLAY_ENG_MODE                  (RIL_OEM_UNSOL_RESPONSE_BASE + 200)
#define RIL_UNSOL_OEM_AM                                (RIL_OEM_UNSOL_RESPONSE_BASE + 201)
#define RIL_UNSOL_OEM_PIN_CONTROL                       (RIL_OEM_UNSOL_RESPONSE_BASE + 202)
#define RIL_UNSOL_OEM_VSIM_OPERATION                    (RIL_OEM_UNSOL_RESPONSE_BASE + 203)

/* WFC */
#define RIL_UNSOL_OEM_WFC_RTP_RTCP_TIMEOUT                  (RIL_OEM_UNSOL_RESPONSE_BASE + 300)
#define RIL_UNSOL_OEM_WFC_FIRST_RTP                         (RIL_OEM_UNSOL_RESPONSE_BASE + 301)
#define RIL_UNSOL_OEM_WFC_RTCP_RX_SR                        (RIL_OEM_UNSOL_RESPONSE_BASE + 302)
#define RIL_UNSOL_OEM_WFC_RCV_DTMF_NOTI                     (RIL_OEM_UNSOL_RESPONSE_BASE + 303)
#define RIL_UNSOL_OEM_WFC_SIGNAL_STRENGTH                   (RIL_OEM_UNSOL_RESPONSE_BASE + 304)

/* eMBMS */
#define RIL_UNSOL_OEM_EMBMS_COVERAGE                        (RIL_OEM_UNSOL_RESPONSE_BASE + 350)
#define RIL_UNSOL_OEM_EMBMS_SESSION_LIST                    (RIL_OEM_UNSOL_RESPONSE_BASE + 351)
#define RIL_UNSOL_OEM_EMBMS_SIGNAL_STRENGTH                 (RIL_OEM_UNSOL_RESPONSE_BASE + 352)
#define RIL_UNSOL_OEM_EMBMS_NETWORK_TIME                    (RIL_OEM_UNSOL_RESPONSE_BASE + 353)
#define RIL_UNSOL_OEM_EMBMS_SAI_LIST                        (RIL_OEM_UNSOL_RESPONSE_BASE + 354)
#define RIL_UNSOL_OEM_EMBMS_GLOBAL_CELL_ID                  (RIL_OEM_UNSOL_RESPONSE_BASE + 355)
#define RIL_UNSOL_OEM_EMBMS_RADIO_STATE_CHANGED             (RIL_OEM_UNSOL_RESPONSE_BASE + 356)
#define RIL_UNSOL_OEM_EMBMS_MODEM_STATUS                    (RIL_OEM_UNSOL_RESPONSE_BASE + 357)
#define RIL_UNSOL_OEM_EMBMS_SESSION_CONTROL                 (RIL_OEM_UNSOL_RESPONSE_BASE + 358)

/*
 * OEM specific
 */
#define RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE                (RIL_OEM_UNSOL_RESPONSE_BASE + 1000)
/******************** OEM2 ********************/
#define RIL_UNSOL_OEM_SAR_RF_CONNECTION                     (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 1)
#define RIL_UNSOL_OEM_CA_BANDWIDTH_FILTER                   (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 2)

/******************** OEM5 ********************/
#define RIL_UNSOL_OEM_SELFLOG_STATUS                        (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 40)
#define RIL_UNSOL_OEM_MODEM_INFO                            (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 41)
#define RIL_UNSOL_OEM_RTP_PKTLOSS_THRESHOLD                 (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 42)
#define RIL_UNSOL_OEM_FREQUENCY_INFO                        (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 43)
#define RIL_UNSOL_OEM_AMBR                                  (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 44)
#define RIL_UNSOL_B2_B1_CONFIG_INFO                         (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 45)

#endif // _RIL_OEM_H
